### ISSUE TITLE
Can't figure out how to edit mob health.

### ISSUE THREAD

**Issue by tacticalretard** [Darkhax-Minecraft/Damage-Control#1]
In the description of your mod on CurseForge, it states that you can change both the global health of all entities and the individual health of specific mobs. I found the global health modifier in the config file, but I cannot figure out how to change the health of individual mobs.

Features

Max Health Manipulation - _You can raise, or lower the max health of specific mobs._ For example, you can set creepers to have 5 hearts instead of 10, or make bats have 1000 hearts.

**Comment by Darkhax** [comment]
When you load up a world, it will auto-generate configurations for all the mobs in your pack instance. 

```
max_health {
    # The maximum health value for minecraft:bat [range: 0.0 ~ 1024.0, default: 6.0]
    S:"MaxHealth_minecraft:bat"=6.0

    # The maximum health value for minecraft:blaze [range: 0.0 ~ 1024.0, default: 20.0]
    S:"MaxHealth_minecraft:blaze"=20.0

    # The maximum health value for minecraft:cave_spider [range: 0.0 ~ 1024.0, default: 12.0]
    S:"MaxHealth_minecraft:cave_spider"=12.0
}
