### ISSUE TITLE
Enhancement: Option to multiply damage from mobs in other dimensions!

### ISSUE THREAD

**Issue by SirAron111** [Darkhax-Minecraft/Damage-Control#11]
Enhancement: Option to multiply damage from mobs in other dimensions!
This would enable me for example to set a general extra damage modifier for enemies in other dimension without increasing the mob damage in the over world.

This would help balancing modded dimensions and so on to for example make mobs in the mining world from aroma more dangerous or make the mobs in the aether do more damage even against people who already have a tone of armor. Without making over world mobs even stronger.

So if I set for example mob damage general to x2.5 mobs in the over world do 2.5 the damage. And if I set the dimension modifier for “dimension -6” (let’s say it grabs all the possible dimensions like it does with all the possible damage sources) to x2 it would give me an end result of the x25 that amplifies the damage and than a x2 o basically mobdmg*2.5*2 in dimension -6 while keeping the simple x2.5 for all others not specifically set.

Also is it in any way possible to separate the damage source from arrows? Since setting arrow damage up sadly not only increases skeletons damage but also player damage. (Setting general or mob damage source doesn’t affect skelli bow shots only skelli melee)

**Comment by Darkhax** [comment]
This would be a cool idea. Unfortunately I don't think Damage control is set up to include this type of thing in it's scope. The intended use case for this mod is to allow for finer degrees of adjustment with health and damage when it comes to balancing and progression in a pack. For example many MMOs will give players hundreds or thousands of health points, allowing them to more room for balancing weapons, enemies, and bosses.

**Comment by SirAron111** [comment]
Yes and that is exactly what I am using this mod for its a core feature of my modpack “Dimension Zero” that mobs start out with these settings. And then get scaled up over time by the scaling health mod with even more extra dmg and extra hp it’s just that there are way more mods providing overpowered armor and tools and even with all the tweaking I did at some point most players don’t have any challenge anymore even if mobs do extra dmg. When they finally decide it’s time to tackle some bosses. Well maybe this idea is for another mod than to get extra parameters set for specific dimension like extra dmg multiplier for dimension X or extra mob speed in dimension Y armor pierce % in dimension Z or something like that but thx for reading this jumble of an idea XD

**Comment by Darkhax** [comment]
This project is no longer being supported and has been discontinued.
