### ISSUE TITLE
Various mod are crashing when creating world and Health changes don't apply 

### ISSUE THREAD

**Issue by Crix310** [Darkhax-Minecraft/Damage-Control#14]
As I wrote in the title, when I load the world many mods crash and I didn't find anything related to this problem on the internet. Is there a solution? Sorry for wrong english

**Comment by Darkhax** [comment]
Hi, I need the crash log to help you.

**Comment by Crix310** [comment]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2020-08-05 15:52:09 CEST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at net.minecraft.network.play.server.SPacketEntityStatus.getEntity(SourceFile:42)
    at net.minecraft.client.network.NetHandlerPlayClient.handleEntityStatus(NetHandlerPlayClient.java:1005)
    at net.minecraft.network.play.server.SPacketEntityStatus.processPacket(SourceFile:38)
    at net.minecraft.network.play.server.SPacketEntityStatus.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 9 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1303637712 bytes (1243 MB) / 4571791360 bytes (4360 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9216m -Xms256m -XX:PermSize=256m
  IntCache: cache: 13, tcache: 95, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 141 mods loaded, 141 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                    | Version               | Source                                             | Signature                                |
       |:------ |:--------------------- |:--------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft             | 1.12.2                | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                   | 9.42                  | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                   | 8.0.99.99             | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                 | 14.23.5.2854          | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | ivtoolkit             | 1.3.3-1.12            | minecraft.jar                                      | None                                     |
       | LCHIJA | foamfixcore           | 7.7.4                 | minecraft.jar                                      | None                                     |
       | LCHIJA | swordskillsapi        | 1.1.0                 | 1.12.2-SwordSkillsApi-1.1.0.jar                    | None                                     |
       | LCHIJA | dynamicswordskills    | 1.12.2-6.0.1          | 1.12.2-DynamicSwordSkills-6.0.1.jar                | None                                     |
       | LCHIJA | antiqueatlas          | 4.6.3                 | antiqueatlas-1.12.2-4.6.3.jar                      | None                                     |
       | LCHIJA | reccomplex            | 1.4.8.2               | RecurrentComplex-1.4.8.2.jar                       | None                                     |
       | LCHIJA | aarcaddon             | 1.0.1                 | AARCAddon-1.0.1.jar                                | None                                     |
       | LCHIJA | orbis-lib             | 0.2.0                 | orbis-lib-1.12.2-0.2.0+build411.jar                | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | LCHIJA | aether                | 0.3.0                 | aether_ii-1.12.2-0.3.0+build411-universal.jar      | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | LCHIJA | aether_legacy         | 1.4.4                 | aether_legacy-1.12.2-v1.4.4.jar                    | None                                     |
       | LCHIJA | biomesoplenty         | 7.0.1.2441            | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
       | LCHIJA | baubles               | 1.5.2                 | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJA | jei                   | 4.15.0.296            | jei_1.12.2-4.15.0.296.jar                          | None                                     |
       | LCHIJA | thaumcraft            | 6.1.BETA26            | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
       | LCHIJA | botania               | r1.10-363             | Botania r1.10-363.jar                              | None                                     |
       | LCHIJA | craftstudioapi        | 1.0.0                 | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LCHIJA | harvestcraft          | 1.12.2zb              | Pam's HarvestCraft 1.12.2zg.jar                    | None                                     |
       | LCHIJA | ctm                   | MC1.12.2-1.0.2.31     | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
       | LCHIJA | twilightforest        | 3.10.1013             | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
       | LCHIJA | animania              | 1.7.3                 | animania-1.12.2-1.7.3.jar                          | None                                     |
       | LCHIJA | antiqueatlasoverlay   | 1.2                   | antiqueatlas-1.12.2-4.6.3.jar                      | None                                     |
       | LCHIJA | aoa3                  | 3.3.2                 | AoA3-3.3.2.jar                                     | 8bddeac148843f40e0b9f69201be2f4b3071700d |
       | LCHIJA | aquaculture           | 1.6.8                 | Aquaculture-1.12.2-1.6.8.jar                       | None                                     |
       | LCHIJA | astralsorcery         | 1.10.25               | astralsorcery-1.12.2-1.10.25.jar                   | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCHIJA | atum                  | 2.0.17                | Atum-1.12.2-2.0.17.jar                             | None                                     |
       | LCHIJA | quark                 | r1.6-179              | Quark-r1.6-179.jar                                 | None                                     |
       | LCHIJA | autoreglib            | 1.3-32                | AutoRegLib-1.3-32.jar                              | None                                     |
       | LCHIJA | beasts                | 1.2                   | Beasts-1.12.2-1.2.1.jar                            | None                                     |
       | LCHIJA | bettercaves           | 1.12.2                | bettercaves-1.12.2-2.0.4.jar                       | None                                     |
       | LCHIJA | bettermineshafts      | 1.12.2-1.3            | BetterMineshaftsForge-1.12.2-1.3.jar               | None                                     |
       | LCHIJA | guideapi              | 1.12-2.1.8-63         | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
       | LCHIJA | bloodmagic            | 1.12.2-2.4.3-105      | BloodMagic-1.12.2-2.4.3-105.jar                    | None                                     |
       | LCHIJA | bloodmoon             | 1.5.3                 | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | blue_skies            | 1.1.3                 | blue_skies-1.12.2-v1.1.3.jar                       | None                                     |
       | LCHIJA | bookshelf             | 2.3.590               | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | bookworm              | 1.12.2-2.5.2.1        | bookworm-1.12.2-2.5.2.1.jar                        | None                                     |
       | LCHIJA | bountifulbaubles      | 0.0.1                 | Bountiful Baubles-1.12.2-0.1.6.jar                 | None                                     |
       | LCHIJA | forgelin              | 1.8.4                 | Forgelin-1.8.4.jar                                 | None                                     |
       | LCHIJA | bountiful             | 2.2.2                 | Bountiful-2.2.2.jar                                | None                                     |
       | LCHIJA | cavern                | 2.3.1                 | Cavern_1.12.2-v2.3.1.jar                           | None                                     |
       | LCHIJA | chameleon             | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | LCHIJA | champions             | 1.12.2-1.0.11.9       | champions-1.12.2-1.0.11.9.jar                      | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | roots                 | 1.12.2-3.0.30         | Roots-1.12.2-3.0.30.jar                            | None                                     |
       | LCHIJA | mysticalworld         | 1.12.2-1.8.4          | mysticalworld-1.12.2-1.8.4.jar                     | None                                     |
       | LCHIJA | chisel                | MC1.12.2-1.0.2.45     | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
       | LCHIJA | chococraft            | 0.9.8.0               | chococraft_1.12.2-0.9.8.0.jar                      | None                                     |
       | LCHIJA | llibrary              | 1.7.19                | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | cqrepoured            | 1.21.0A               | Chocolate_Quest_Repoured-1.12.2-1.21.0A.jar        | None                                     |
       | LCHIJA | cosmeticarmorreworked | 1.12.2-v5a            | CosmeticArmorReworked-1.12.2-v5a.jar               | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | dmgcontrol            | 1.3.15                | DamageControl-1.12.2-1.3.15.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | dawnoftimebuilder     | 1.0.7                 | dawnoftime_builder_edition-1.0.7.jar               | None                                     |
       | LCHIJA | dldungeonsjbg         | 1.13.2                | DoomlikeDungeons-1.13.2-MC1.12.2.jar               | None                                     |
       | LCHIJA | orelib                | 3.6.0.1               | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround             | 3.6.1.0               | DynamicSurroundings-1.12.2-3.6.1.0.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dynamictrees          | 1.12.2-0.9.8          | DynamicTrees-1.12.2-0.9.8.jar                      | None                                     |
       | LCHIJA | dynamictreesbop       | 1.12.2-1.4.1e         | DynamicTreesBOP-1.12.2-1.4.1e.jar                  | None                                     |
       | LCHIJA | dynamictreesphc       | 1.12.2-1.4.2          | DynamicTreesPHC-1.12.2-1.4.2.jar                   | None                                     |
       | LCHIJA | dynamictreesquark     | 1.12.2-1.0.4          | dynamictreesQuark-1.12.2-1.0.4.jar                 | None                                     |
       | LCHIJA | dynamictreesroots     | 0.2.1                 | dynamicTreesRoots-0.2.1.jar                        | None                                     |
       | LCHIJA | rustic                | 1.1.4                 | rustic-1.1.4.jar                                   | None                                     |
       | LCHIJA | dynamictreestc        | 1.12.2-1.4.1e         | DynamicTreesTC-1.12.2-1.4.1e.jar                   | None                                     |
       | LCHIJA | dynamictreestheaether | 1.12.2-1.0.4          | dynamictreesTheAether-1.12.2-1.0.4.jar             | None                                     |
       | LCHIJA | dynamictreesttf       | 1.12.2-1.1.2          | dynamictreesTheTwilightForest-1.12.2-1.1.2.jar     | None                                     |
       | LCHIJA | ebwizardry            | 4.2.11                | ElectroblobsWizardry-4.2.11-MC1.12.2.jar           | None                                     |
       | LCHIJA | csb_ench_table        | 1.1.3                 | EnchantingTable-1.12-1.1.3.jar                     | None                                     |
       | LCHIJA | endreborn             | 0.3.8                 | EndReborn [0.3.9].jar                              | None                                     |
       | LCHIJA | erebus                | 1.0.31                | Erebus-1.0.31.jar                                  | None                                     |
       | LCHIJA | exoticbirds           | 1.0                   | Exotic Birds 1.12.2-3.2.0.jar                      | None                                     |
       | LCHIJA | mod_lavacow           | 1.1.0                 | Fish's Undead Rising-1.1.0b.jar                    | None                                     |
       | LCHIJA | foamfix               | 0.10.10-1.12.2        | foamfix-0.10.10-1.12.2.jar                         | None                                     |
       | LCHIJA | ftblib                | 5.4.7.2               | FTBLib-5.4.7.2.jar                                 | None                                     |
       | LCHIJA | itemfilters           | 1.0.4.2               | ItemFilters-1.0.4.2.jar                            | None                                     |
       | LCHIJA | ftbquests             | 1.9.0.12              | FTBQuests-1.9.0.12.jar                             | None                                     |
       | LCHIJA | ftbmoney              | 1.2.0.47              | FTBMoney-1.2.0.47.jar                              | None                                     |
       | LCHIJA | cfm                   | 6.3.1                 | furniture-6.3.1-1.12.2.jar                         | None                                     |
       | LCHIJA | futureminecraf        | 1.3.0.2               | FutureVersions v1.3.0.2.jar                        | None                                     |
       | LCHIJA | glacidus              | 1.2.1                 | Glacidus-1.12.2-v1.2.1.jar                         | None                                     |
       | LCHIJA | gravestone            | 1.10.3                | gravestone-1.10.3.jar                              | None                                     |
       | LCHIJA | hammercore            | 2.0.6.19              | HammerLib-1.12.2-2.0.6.19.jar                      | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | huntingdim            | 1.0.42                | HuntingDimension-1.12.2-1.0.42.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | waila                 | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | LCHIJA | iceandfire            | 1.9.1                 | iceandfire-1.9.1-1.12.2.jar                        | None                                     |
       | LCHIJA | ignitehud             | b0.5.4                | IgniteHUD-b0.5.4.jar                               | None                                     |
       | LCHIJA | illagers_plus         | 1.1                   | IllagersPlus-1.12.2-1.1.3.jar                      | None                                     |
       | LCHIJA | improvableskills      | 65r                   | ImprovableSkills-1.12.2-65r.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | jehc                  | 1.7.2                 | just-enough-harvestcraft-1.12.2-1.7.2.jar          | None                                     |
       | LCHIJA | jeid                  | 1.0.3-55              | JustEnoughIDs-1.0.3-55.jar                         | None                                     |
       | LCHIJA | libraryex             | 1.1.3                 | LibraryEx-1.12.2-1.1.3.jar                         | None                                     |
       | LCHIJA | login_shield          | 1.12.2-6-g5654706     | Login_Shield-1.12.2-6-g5654706.jar                 | None                                     |
       | LCHIJA | malisiscore           | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
       | LCHIJA | malisisdoors          | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
       | LCHIJA | som                   | 1.2.10-mc1.12.2       | MK1.12.2-1.2.10.jar                                | None                                     |
       | LCHIJA | moreemerald           | 1.4.1 - 1.12.2        | MoreEmerald-1.4.1.jar                              | None                                     |
       | LCHIJA | mowziesmobs           | 1.5.6                 | mowziesmobs-1.5.6.jar                              | None                                     |
       | LCHIJA | multimob              | 1.0.5                 | multimob-1.0.5.jar                                 | None                                     |
       | LCHIJA | mutantbeasts          | 1.12.2-0.7.2          | MutantBeasts-1.12.2-0.7.2.jar                      | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
       | LCHIJA | naturescompass        | 1.8.5                 | NaturesCompass-1.12.2-1.8.5.jar                    | None                                     |
       | LCHIJA | netherex              | 2.1.8                 | NetherEx-1.12.2-2.1.8.jar                          | None                                     |
       | LCHIJA | paraglider            | 1.0.1.5               | Paraglider-1.12.2-1.0.1.5.jar                      | None                                     |
       | LCHIJA | patchouli             | 1.0-21                | Patchouli-1.0-21.jar                               | None                                     |
       | LCHIJA | primitivemobs         | 1.2.3a                | primitivemobs-1.2.3a.jar                           | None                                     |
       | LCHIJA | rats                  | 3.2.13                | rats-3.2.13-1.12.2.jar                             | None                                     |
       | LCHIJA | xreliquary            | 1.12.2-1.3.4.796      | Reliquary-1.12.2-1.3.4.796.jar                     | None                                     |
       | LCHIJA | roguelike             | 1.8.0                 | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
       | LCHIJA | roughmobs             | 2.0.0                 | roughmobs2-1.12.2_2.0.15.jar                       | None                                     |
       | LCHIJA | savemystronghold      | 1.12.2-1.0.0          | savemystronghold-1.12.2-1.0.0.jar                  | None                                     |
       | LCHIJA | silentlib             | 3.0.13                | SilentLib-1.12.2-3.0.14+168.jar                    | None                                     |
       | LCHIJA | scalinghealth         | 1.3.37                | ScalingHealth-1.12.2-1.3.42+147.jar                | None                                     |
       | LCHIJA | simpledivegear        | 1.1.1                 | SimpleDivingGear-1.1.1 mc 1.12.2.jar               | None                                     |
       | LCHIJA | spartanweaponry       | beta 1.3.8            | SpartanWeaponry-1.12.2-beta-1.3.8.jar              | None                                     |
       | LCHIJA | spartanfire           | 0.08                  | spartanfire-0.08.jar                               | None                                     |
       | LCHIJA | spartanshields        | 1.5.4                 | SpartanShields-1.12.2-1.5.4.jar                    | None                                     |
       | LCHIJA | spartanweaponryarcana | beta 1.0.3            | SpartanWeaponryArcana-1.12.2-beta-1.0.3.jar        | None                                     |
       | LCHIJA | stepup                | 1.0.2-mc1.10-1.12.2   | StepUp-1.0.2-mc1.10-1.12.jar                       | None                                     |
       | LCHIJA | storagedrawers        | 5.2.2                 | StorageDrawers-1.12.2-5.4.2.jar                    | None                                     |
       | LCHIJA | stygian               | 1.0.4                 | stygian-1.0.4.jar                                  | None                                     |
       | LCHIJA | tfspellpack           | 1.0.2                 | TFSpellPack-1.0.2-MC1.12.2.jar                     | None                                     |
       | LCHIJA | thaumicaugmentation   | 1.12.2-1.1.19         | ThaumicAugmentation-1.12.2-1.1.19.jar              | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCHIJA | theabyss              | 2.1.0                 | TheAbyss 2.7.5b3 1.12.2.jar                        | None                                     |
       | LCHIJA | toolbelt              | 1.9.13                | ToolBelt-1.12.2-1.9.13.jar                         | None                                     |
       | LCHIJA | torohealthmod         | 1.12.2-11             | torohealth-1.12.2-11.jar                           | None                                     |
       | LCHIJA | travelersbackpack     | 1.0.33                | TravelersBackpack-1.12.2-1.0.33.jar                | None                                     |
       | LCHIJA | tropicraft            | 7.1.9.115             | tropicraft-MC1.12.2-7.1.9.115.jar                  | None                                     |
       | LCHIJA | vanillafix            | 1.0.10-150            | VanillaFix-1.0.10-150.jar                          | None                                     |
       | LCHIJA | idk                   | 1.0.0                 | VPPVu4.jar                                         | None                                     |
       | LCHIJA | wailaharvestability   | 1.1.12                | WailaHarvestability-mc1.12-1.1.12.jar              | None                                     |
       | LCHIJA | wawla                 | 2.6.275               | Wawla-1.12.2-2.6.275.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | waystones             | 4.1.0                 | Waystones_1.12.2-4.1.0.jar                         | None                                     |
       | LCHIJA | wrd                   | 0.8.0                 | Wesley's Roguelike Dungeons V0.8.1.jar             | None                                     |
       | LCHIJA | zawa                  | 1.12.2-2.1.0          | zawa-1.12.2-2.1.0.jar                              | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
       | LCHIJA | phosphor-lighting     | 1.12.2-0.2.6          | phosphor-1.12.2-0.2.6+build50-universal.jar        | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | immersiveengineering  | 0.12-98               | ImmersiveEngineering-0.12-98.jar                   | None                                     |
       | LCHIJA | reauth                | 3.6.0                 | reauth-3.6.0.jar                                   | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | LCHIJA | snowrealmagic         | 0.3.3                 | SnowRealMagic-0.3.3.jar                            | None                                     |
       | LCHIJA | thebetweenlands       | 3.6.2                 | TheBetweenlands-3.6.2-universal.jar                | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCHIJA | midnight              | 0.3.5                 | themidnight-0.3.5.jar                              | None                                     |
       | LCHIJA | mysticallib           | 1.12.2-1.7.0          | mysticallib-1.12.2-1.7.0.jar                       | None                                     |
  Loaded coremods (and transformers): TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      midnight (themidnight-0.3.5.jar)
                                        com.mushroom.midnight.core.transformer.MidnightClassTransformer
                                      ParagliderLoadingPlugin (Paraglider-1.12.2-1.0.1.5.jar)
                                        com.tictim.paraglider.asm.TransformerModelBiped
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      HCASM (HammerLib-1.12.2-2.0.6.19.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      AstralCore (astralsorcery-1.12.2-1.10.25.jar)
                                        
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      ratscore (rats-3.2.13-1.12.2.jar)
                                        com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.2-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-1.1.19.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14736 Compatibility Profile Context 20.7.2 27.20.2001.9003' Renderer: 'Radeon RX 570 Series'
  HammerCore Debug Information: Dependent Mods:
                                    -Improvable Skills (improvableskills) @65r
  Patchouli open book context: n/a
  Suspected Mods: Unknown

**Comment by Crix310** [comment]
Edit: I've just discovered that VanillaFix was the problem. There are no longer crash errors by removing that mod.

**Comment by Crix310** [comment]
I have encountered another issue: health changes don't apply. When I save the config file there aren't any changes on the world and the config file just resets. Any solution to this?

**Comment by Darkhax** [comment]
This project is no longer being supported and has been discontinued.
