### ISSUE TITLE
Compatibility issue when used together with other mods that alter health.

### ISSUE THREAD

**Issue by SirAron111** [Darkhax-Minecraft/Damage-Control#8]
Hello I have found an annoying issue with the mod.

Namely the fact that when used together with mods that alter health like scaling health, bauble heart canisters, sol carrot and the like, it forces health values down to the set basic values every time I log back in. this forces me to regen back my health to max every time I relog and that mobs who had their hp altered were forced down to base health to.

For the player it’s pretty annoying that he has to regen back up since it costs hunger to do so especially with over 200 hp

On the other hand mobs will be reduced to the registered base values making relogs abuse able to easily defeat upscale mob with the upscale damages.

Can you implement an option to turn off the hp altering for player and mobs? Since I like the mod for its damage alteration effects which are really when combined with scaling health mod good since I can decide what does more damage and what not.

**Comment by SirAron111** [comment]
It also forces slimes and dragons (from a deifferent mod) to no mather what stage they are in to have the set base amount of health. and its no fun fighting a 200hp baby slime

**Comment by Riernar** [comment]
Hello everyone,

While using this mod in a custom modpack, I encountered the same issue. I tried to help implement a fix and made the above pull request.
I new to modding and git, so please do not hesitate to tell me if I've done anything not in the preferred way.
I couldn't test yet as my dev environment crashes when I try to add the one probe to look at the health of mobs. I'll try to fix that.

Hope this helps !

**Comment by Darkhax** [comment]
Riernar's PR should help fix your issue.
