### ISSUE TITLE
Wither boss does not heal to configured max HP

### ISSUE THREAD

**Issue by schindlershadow** [Darkhax-Minecraft/Damage-Control#9]
Wither boss does not heal to configured max HP. 

mine is set to 8000 but when it spawns it only heals up to 300, the default.

DamageControl-1.12.2-1.3.15

**Comment by Darkhax** [comment]
Thanks for the issue report. Unfortunately this is a vanilla bug and not really something I can fix. The wither boss does not respect it's max health value.
